// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Worker.Data;

#nullable disable

namespace Worker.Migrations
{
	[DbContext(typeof(AppDbContext))]
	partial class AppDbContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "9.0.14")
				.HasAnnotation("Relational:MaxIdentifierLength", 63);

			NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

			modelBuilder.Entity("Worker.Data.Entities.Analog", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

					b.Property<int>("MedicineId")
						.HasColumnType("integer");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("text");

					b.HasKey("Id");

					b.HasIndex("MedicineId");

					b.ToTable("Analogs");
				});

			modelBuilder.Entity("Worker.Data.Entities.Maker", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

					b.Property<DateTimeOffset>("CertExpiryDate")
						.HasColumnType("timestamp with time zone");

					b.Property<DateTimeOffset>("CertIssueDate")
						.HasColumnType("timestamp with time zone");

					b.Property<string>("CertNumber")
						.IsRequired()
						.HasColumnType("text");

					b.Property<string>("CertOrganization")
						.IsRequired()
						.HasColumnType("text");

					b.Property<string>("DosageAmount")
						.IsRequired()
						.HasColumnType("text");

					b.Property<string>("DosageFrequency")
						.IsRequired()
						.HasColumnType("text");

					b.Property<int>("MedicineVersionId")
						.HasColumnType("integer");

					b.Property<decimal>("PackagePrice")
						.HasColumnType("numeric");

					b.Property<int>("PackageQuantity")
						.HasColumnType("integer");

					b.Property<string>("PackageType")
						.IsRequired()
						.HasColumnType("text");

					b.HasKey("Id");

					b.HasIndex("MedicineVersionId");

					b.ToTable("Makers");
				});

			modelBuilder.Entity("Worker.Data.Entities.Medicine", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

					b.Property<string>("Group")
						.IsRequired()
						.HasColumnType("text");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("text");

					b.Property<string>("Pharm")
						.IsRequired()
						.HasColumnType("text");

					b.HasKey("Id");

					b.ToTable("Medicines");
				});

			modelBuilder.Entity("Worker.Data.Entities.MedicineVersion", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

					b.Property<int>("MedicineId")
						.HasColumnType("integer");

					b.Property<string>("Type")
						.IsRequired()
						.HasColumnType("text");

					b.HasKey("Id");

					b.HasIndex("MedicineId");

					b.ToTable("MedicineVersions");
				});

			modelBuilder.Entity("Worker.Data.Entities.Analog", b =>
				{
					b.HasOne("Worker.Data.Entities.Medicine", "Medicine")
						.WithMany("Analogs")
						.HasForeignKey("MedicineId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("Medicine");
				});

			modelBuilder.Entity("Worker.Data.Entities.Maker", b =>
				{
					b.HasOne("Worker.Data.Entities.MedicineVersion", "MedicineVersion")
						.WithMany("Makers")
						.HasForeignKey("MedicineVersionId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("MedicineVersion");
				});

			modelBuilder.Entity("Worker.Data.Entities.MedicineVersion", b =>
				{
					b.HasOne("Worker.Data.Entities.Medicine", "Medicine")
						.WithMany("Versions")
						.HasForeignKey("MedicineId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("Medicine");
				});

			modelBuilder.Entity("Worker.Data.Entities.Medicine", b =>
				{
					b.Navigation("Analogs");

					b.Navigation("Versions");
				});

			modelBuilder.Entity("Worker.Data.Entities.MedicineVersion", b =>
				{
					b.Navigation("Makers");
				});
#pragma warning restore 612, 618
		}
	}
}
